### ISSUE TITLE
About helpers/nn_mri.py file  and import lrelu 

### ISSUE THREAD

**Issue by fharman** [zaccharieramzi/fastmri-reproducible-benchmark#101]
Hi everyone,

For the testing , i want to run **qualitative_validation_for_net.ipynb**. But   there is an error  in this line.

_from fastmri_recon.helpers.nn_mri import lrelu_

 No module named '**fastmri_recon.helpers**'

In fastmri_recon folder , there is no **helpers folder** and  consequently there is no file  named  **nn_mri.py** in **helpers** folder.

Is there any problem while uploading the helpers folder and its contexts?

Best regards,

**Comment by zaccharieramzi** [comment]
Hi Fatma,

Yes this is to be expected in those notebooks as they are pretty old now and not maintained. They should still provide a good basis for testing the networks trained with the functional API, so you could try to  just prune them to what you need.

When I have time I will try to correct them in order to have them work in the current state, or even better provide evaluation scripts for the functional networks.

**Comment by fharman** [comment]
> etty old now and not maintained. They should still provide a good basis for testing the networks trained with the functional API, so you could try to just prune them to what you need.

thank you, i am waiting for your information

**Comment by fharman** [comment]
Hello again,

when i prune the code for reconstruction(comment all lines that included helpers folder), i encountered another problem that included helpers folder.

_from fastmri_recon.helpers.reconstruction import reco_and_gt_unet_from_val_file, reco_and_gt_net_from_val_file, reco_and_gt_zfilled_from_val_file_

As it is seen, in **reconstruction.py** ,  it is needed to import  **reco_and_gt_unet_from_val_file**. In **all_net_params** section,

 _'val_gen': val_gen_zero,
        'run_id': 'unet_af4_1569210349',
        'reco_function': reco_and_gt_unet_from_val_file,
    },_

these lines calls the _**reco_and_gt_unet_from_val_file**_ for the reconstruction.  So  **helpers** folder contains all these **reconstruction.py** and  **nn_mri.py**  files.

best regards,

**Comment by zaccharieramzi** [comment]
Sorry about that. 
- You can find `reco_and_gt_unet_from_val_file` in [`fastmri_recon.evaluate.reconstruction.unet_reconstruction.py`](https://github.com/zaccharieramzi/fastmri-reproducible-benchmark/blob/master/fastmri_recon/evaluate/reconstruction/unet_reconstruction.py).
- You can find `reco_and_gt_net_from_val_file` in [`fastmri_recon.evaluate.reconstruction.cross_domain_reconstruction.py`](https://github.com/zaccharieramzi/fastmri-reproducible-benchmark/blob/master/fastmri_recon/evaluate/reconstruction/cross_domain_reconstruction.py).
- You can find `reco_and_gt_zfilled_from_val_file` in [fastmri_recon.evaluate.reconstruction.zero_filled_reconstruction.py](https://github.com/zaccharieramzi/fastmri-reproducible-benchmark/blob/master/fastmri_recon/evaluate/reconstruction/zero_filled_reconstruction.py)

**Comment by fharman** [comment]
> Sorry about that.
> 
> * You can find `reco_and_gt_unet_from_val_file` in [`fastmri_recon.evaluate.reconstruction.unet_reconstruction.py`](https://github.com/zaccharieramzi/fastmri-reproducible-benchmark/blob/master/fastmri_recon/evaluate/reconstruction/unet_reconstruction.py).
> * You can find `reco_and_gt_net_from_val_file` in [`fastmri_recon.evaluate.reconstruction.cross_domain_reconstruction.py`](https://github.com/zaccharieramzi/fastmri-reproducible-benchmark/blob/master/fastmri_recon/evaluate/reconstruction/cross_domain_reconstruction.py).
> * You can find `reco_and_gt_zfilled_from_val_file` in [`fastmri_recon.evaluate.reconstruction.zero_filled_reconstruction.py`](https://github.com/zaccharieramzi/fastmri-reproducible-benchmark/blob/master/fastmri_recon/evaluate/reconstruction/zero_filled_reconstruction.py)

ok i will revise it. thank you:)

**Comment by fharman** [comment]
Hi again,

Sorry for disturbance.  But  i encountered the problem in **_all_net_params_** section named **NameError: name 'lrelu' is not defined**.

This function is derived from  nonexisting **nn_mri.py**. Because **lrelu** is tried to import from there.  Consequently, testing is not run .

**Comment by zaccharieramzi** [comment]
Hmm but did you use `lrelu` in your unet model ?

If so then the simplest I can do is just to add in an evaluation notebook to cover the old models.

**Comment by fharman** [comment]
Hi, i just only used unet from ../models/.functional_models/unet.

Zaccharie Ramzi <notifications@github.com>, 19 Eki 2020 Pzt, 11:02
tarihinde şunu yazdı:

**Comment by zaccharieramzi** [comment]
If you used the current parameters listed in `unet_approach_af4.py` you don't need `lrelu`.

**Comment by fharman** [comment]
I changed before you mailed me. Thank you for your support,

Best regards

19 Eki 2020 Pzt 12:00 tarihinde Zaccharie Ramzi <notifications@github.com>
şunu yazdı:

**Comment by fharman** [comment]
Hi everyone again,

Sorry for disturbance. But while running the **qualitative_validation_for_net** for unet , i encountered the error named  as

_ValueError: You are trying to load a weight file containing 19 layers into a model with 60 layers._

But As you know, anyway  unet has 19 layers. I don't understand why i am always facing this error.

Do you have any idea for this?

Best regards,

**Comment by zaccharieramzi** [comment]
It probably means that you haven't used the same parameters for training and for evaluation. Make sure that the parameters match.

Btw, a U-net doesn't always have 19 layers, it depends on how you define layer and also on how you parametrize the U-net instance.

**Comment by fharman** [comment]
Sorry i was confused with vgg16 because of training fastmri both VGG16 and UNET at the same time. I changed the path as your folder 

 **_chkpt_path = f'/content/fastmri_reproducible_benchmark_master/checkpoints/{run_id}-{epoch}.hdf5'_** . I think this error is derived because of the model that i trained more less fastmri data.

But after changing the path as you added in **fastmri_reproducible_benchmark_master/checkpoints**  ended with 300 epoch, i encountered another error. I am really sorry about this error disturbance.

Error is 

**_TypeError: To be compatible with tf.contrib.eager.defun, Python functions must return zero or more Tensors; in compilation of <function unpack_model at 0x7f8ace097400>, found return value of type <class 'tensorflow.python.keras.engine.training.Model'>, which is not a Tensor._**

Do you have any idea to overcome this error? i searched and tested all way but not overcome.

Best regards,

**Comment by zaccharieramzi** [comment]
Can you show me the entire stack trace ?

**Comment by fharman** [comment]
Thank you!

23 Kas 2020 Pzt 14:53 tarihinde Zaccharie Ramzi <notifications@github.com>
şunu yazdı:
