### ISSUE TITLE
About Test Files Number in qualitative_validation_for_net.ipynb in spite of Contrast Selection

### ISSUE THREAD

**Issue by fharman** [zaccharieramzi/fastmri-reproducible-benchmark#109]
Hi everyone,

I want to reconstruct Fastmri Single Coil  Knee Test Dataset with Unet. Because of this, i used testing mode in Zerofilled2DSequence and Mask2DSequence in qualitative_validation_for_net.ipynb  like this.

test_path = '/content/drive/My Drive/UNET_Colab/knee_singlecoil_test_v2/singlecoil_test_v2/'
test_gen_zero = ZeroFilled2DSequence(test_path, af=AF, norm=True, **mode='testing'**,**contrast=None**, mask_seed=0)
test_gen_scaled = Masked2DSequence(test_path, **mode='testing'**, af=AF, scale_factor=1e6, **contrast=None**, mask_seed=0)

**len(test_gen_scaled)
50**

But I know that full Test files in Fastmri Single Coil Knee Dataset  are 108. I checked this as:

**import os
path, dirs, files = next(os.walk("/content/drive/My Drive/UNET_Colab/knee_singlecoil_test_v2/singlecoil_test_v2/"))
file_count = len(files)
print(file_count)
108**

It is true. In Testing mode, there is a problem in spite of none selection of contrast in Zerofilled2DSequence and Mask2Dsequence.

But, in validation dataset, there is no problem of counting seen like this:

val_path = '/content/drive/My Drive/UNET_Colab/knee_singlecoil_val/singlecoil_val/'
val_gen_zero = ZeroFilled2DSequence(val_path, af=AF, norm=True, **mode='validation'**)
val_gen_scaled = Masked2DSequence(val_path, **mode='validation',** af=AF, scale_factor=1e6)

**len(val_gen_scaled)
199**

It is true for validation dataset of FastMRI Single Coil Knee Dataset.

What is the problem in testing mode of Zerofilled2Dsequence and Masked2DSequence?(It is valid problem in commit bcd3fdd,too) I am really confused. Because of this number inconsitency, the reconstruction number of images is conflicted with the total number of slices of test dataset.

If you return, i will appreciate.

Best regards,

**Comment by zaccharieramzi** [comment]
The thing is that you are looking at only the test files with `af=AF`, so it's only about half of them, no matter `AF`. You have to handle the 2 different acceleration factors separately.

I actually already had answered this question [here](https://github.com/zaccharieramzi/fastmri-reproducible-benchmark/issues/108#issuecomment-728016477).

**Comment by fharman** [comment]
Hi Zaccharie,
I was really confused and sorry for misunderstanding.  When i encountered
the same thing in commit  bcd3fdd, i  had to write down in github.

But i still really surprised why  i am choosing both AF=4 and AF=8. Because
all test files are obtained   with AF=4.  Why do i choose AF=8 for the
other half?

Thank you for your return,

Best,

Zaccharie Ramzi <notifications@github.com>, 20 Kas 2020 Cum, 16:17
tarihinde şunu yazdı:

**Comment by zaccharieramzi** [comment]
No no, not all the test files are obtained with `AF=4`.
Half of them are acquired with af4 and the other half with af8.
That's why you have both in the public leaderboard: https://fastmri.org/leaderboards/.

**Comment by fharman** [comment]
Oww thank you very much.I don't know this. When i just looked at test
datasets, i thought these must be AF=4.Because aliasing artifacts were not
valid so much in inverse FFT2 reconstruction.

Thank you again.

Best,

20 Kas 2020 Cum 16:43 tarihinde Zaccharie Ramzi <notifications@github.com>
şunu yazdı:
