### ISSUE TITLE
About fastmri_recon/config.py

### ISSUE THREAD

**Issue by fharman** [zaccharieramzi/fastmri-reproducible-benchmark#116]
Hi,

I want to ask you about  fastmri_recon/config.py.  In test folder, 108 h5(AF4=50, AF8=58) files exist. But  in the main code, as you see there are  120 files .

import os

FASTMRI_DATA_DIR = os.environ.get('FASTMRI_DATA_DIR', '/media/Zaccharie/UHRes/')
OASIS_DATA_DIR = os.environ.get('OASIS_DATA_DIR', '/media/Zaccharie/UHRes/')
LOGS_DIR = os.environ.get('LOGS_DIR', './')
CHECKPOINTS_DIR = os.environ.get('CHECKPOINTS_DIR', './')

n_volumes_train = 973
n_volumes_val = 199
n_volumes_test = {
    4: 60,
    8: 60,
}

Am i wrong about the number of  test files?   

Thank you for your patience and support.

Best Regards,

**Comment by zaccharieramzi** [comment]
Hi @fharman ,

You are not wrong, there are 108 test files.
These 2 numbers are indeed not accurate but it's not too sever: they are used only in harmless places in the code (for `tqdm` logging).
I will fix it in a coming PR.

I see that you are still using an old version of the code. As mentioned [here](https://github.com/zaccharieramzi/fastmri-reproducible-benchmark/issues/115#issuecomment-734426749), you could now safely use the current version with the [dedicated evaluation script](https://github.com/zaccharieramzi/fastmri-reproducible-benchmark/blob/master/fastmri_recon/evaluate/scripts/paper_eval.py) to reproduce the results of the paper.

**Comment by fharman** [comment]
Hi Zaccharie,

I want to ask you about the difference. Because the latest one, I remember
you used (Glorot uniform(Xavier Initialization,), Rectified Adam for
Optimizer, and not used kernel_initializer='he_normal') .But in the new
one, there is a difference I realized.  Why is there a big difference?

Thank you for your return,

Best regards,


Zaccharie Ramzi <notifications@github.com>, 27 Kas 2020 Cum, 00:03
tarihinde şunu yazdı:

**Comment by zaccharieramzi** [comment]
@fharman I am not sure what you mean and I don't think it's related to this question.
Please open a new issue if you have another question.

I closed this with the PR #117 being merged.
