### ISSUE TITLE
Transfer Learning Property  in  Trained Networks (PDNet, CascadeNet, UNet, Kiki-Sep-16)

### ISSUE THREAD

**Issue by GeraldGore** [zaccharieramzi/fastmri-reproducible-benchmark#126]
Hello,

I am curious about transfer learning property of these networks. Can I use these trained networks as if it has transfer learning property? Can I use these checkpoints for that?

Thanks,

**Comment by zaccharieramzi** [comment]
Hi again,

So I am not sure exactly what you mean by transfer learning.
If you mean that you want to fine tune the networks, then you certainly can with low learning rates, on other datasets.
If you mean that you want to use those networks directly on out-of-distribution data, then I couldn't say for sure. I know from experience (a work we submitted to ISMRM 2021), that the most recent networks (i.e. XPDNet) can generalize pretty well to data that was not seen before, but still acquired with a Siemens scanner. However, you can see in the fastMRI 2020 challenge's [paper](https://arxiv.org/abs/2012.06318), that generalization to other vendors is still a challenge to be tackled.
In any case I suggest you try and validate the results.

In both senses, yes you can use the networks's checkpoints.

**Comment by zaccharieramzi** [comment]
Hi @GeraldGore , 

Did this answer your question?

**Comment by GeraldGore** [comment]
Hello,

Sorry for being late. I have been probing transfer learning property of this networks  since that day.  As you all this netwoks are  not vanilla model like Alexnet, GoogleNet.   I am trying to search   whether  there is anyone used a model like in (encoder- decoder) or   functional models or not. But, unfortunately  I could not see. For example,  I wanted to use your last 3 layer in your chechkpoints  for testing  to get different different information per each networks.  But , the researchers used transfer learning  are just only using for feature extraction. 

Thank you for all your return,

Best,

**Comment by zaccharieramzi** [comment]
What is your transfer learning use case?
In other words, what is the task you are trying to apply these networks (or a modified version of them) to?

**Comment by GeraldGore** [comment]
I have used Alexnet, GoogleNet etc  before. But in the literature, it is marked as not efficient using  Alexnet or Googlenet  for mri reconstruction (because of  pretrained natural images). But in your study , these networks are trained for this goal  and  I wanted to use your  checkpoints to test another mri dataset ( in the same contrast) and see the  networks ability  . For example, UNET has better  ability to catch high frequencies than the other networks or  PDNet  has better performance in reconstruction  of  low frequencies than the others etc.

I hope I can explain myself clearly,

Best,

**Comment by zaccharieramzi** [comment]
You could definitely try to use these networks on another dataset, without changing anything in the structure just fine-tuning (or even just trying to use them as is).
Maybe one point that requires attention is the scaling but other than that you should be fine.

I am closing this, since I think there is not an action I can do on my end, but feel free to re-open if you think that there is a problem regarding the networks or their implementation.
