### ISSUE TITLE
maybe remove or update np_metrics

### ISSUE THREAD

**Issue by chaithyagr** [zaccharieramzi/fastmri-reproducible-benchmark#150]
Currently, skimage has updated the location for metrics in 0.18.3. Things work fine with 0.17.2.

Howoever, this causes import issues even if the user does not use it

**Comment by chaithyagr** [comment]
The fiile is here: https://github.com/zaccharieramzi/fastmri-reproducible-benchmark/blob/master/fastmri_recon/evaluate/metrics/np_metrics.py

**Comment by zaccharieramzi** [comment]
Thanks for pointing it out!
Do you want to submit a PR for it or should I?

**Comment by chaithyagr** [comment]
i think i can handle a PR, but do you want it to stay or removed?

**Comment by zaccharieramzi** [comment]
I want the metrics to stay, but we can just update their import and have scikit-image be of version at least 0.18.3
