### ISSUE TITLE
need to specify the scikit-image version in the requirements.txt

### ISSUE THREAD

**Issue by fachra** [zaccharieramzi/fastmri-reproducible-benchmark#151]
Hello,

The function `compare_psnr` could be moved to another place in the latest version (0.18) of `scikit-image`. So the code below will raise an error with the latest skimage. https://github.com/zaccharieramzi/fastmri-reproducible-benchmark/blob/f18a4f7d7fdfcc08fd28c84f2bed8dbdedab4a9a/fastmri_recon/evaluate/metrics/np_metrics.py#L10

Need to specify the version (0.17.2) in the `requirements.txt`.
https://github.com/zaccharieramzi/fastmri-reproducible-benchmark/blob/f18a4f7d7fdfcc08fd28c84f2bed8dbdedab4a9a/requirements.txt#L3

Best,
Chengran

**Comment by zaccharieramzi** [comment]
Hi Chengran,

Thanks for pointing it out!
Do you want to submit a PR for it or should I?

I think btw it's a duplicate with #150

**Comment by fachra** [comment]
Yes, it duplicates with #150. I will close this one.
