### ISSUE TITLE
Regarding sessions of OASIS3 dataset to be downloaded

### ISSUE THREAD

**Issue by jainspoornima** [zaccharieramzi/fastmri-reproducible-benchmark#159]
I have been downloading the OASIS3 dataset for experimenting with the PD-net architecture. I tried downloading using the XNAT desktop client, but it needs some server URL which I don't have. I have gained access to the dataset through access request.
Another way to download is through the scripts given here -https://github.com/NrgXnat/oasis-scripts. I wished to ask which files should I download from here for reproducing PD-net results.
Thanks.

**Comment by zaccharieramzi** [comment]
Hi @jainspoornima ,

Thanks for using this repo!
So I remember downloading a zip for the whole dataset on this page: https://central.xnat.org/app/action/ProjectDownloadAction/project/OASIS3. Is it not available to you?

In any case, I agree that for reproducibility's sake it's better to have the clear list of sessions that need to be downloaded to reproduce the results.
Therefore, I included it in a csv that will soon be on master, but you can already find it [here](https://github.com/zaccharieramzi/fastmri-reproducible-benchmark/pull/160/files#diff-2b8c1e20af87036c8114a8f0ab4349e670a2a6f27b5edb0d4999bf55c5c20fed).
Hope this will help.

Please tell me if you have a hard time reproducing the results.

**Comment by zaccharieramzi** [comment]
It is now on [master](https://github.com/zaccharieramzi/fastmri-reproducible-benchmark/blob/master/OASIS_list.csv).

Therefore I am closing this issue, but feel free to reopen it.

**Comment by jainspoornima** [comment]
Thanks for your prompt reply sir.
The zip download is getting stuck at 'preparing to download' message for me.
And with the csv file you provided, I tried downloading using sh/wget.sh
download files but 0% files are getting downloaded -
[image: image.png]
I am using google colab for the purpose.
Could you possibly help with this?

Thanks and regards,
Poornima Jain

**Comment by zaccharieramzi** [comment]
Unfortunately I won't be able to help straight away, as I am currently writing my thesis.
I suggest you try to contact the xnat support who may be able to help you more efficiently.

**Comment by jainspoornima** [comment]
Okay sir, thanks for your reply.

Regards,
Poornima
