### ISSUE TITLE
GPU->CPU Memcpy failed

### ISSUE THREAD

**Issue by Jacksonm75** [zaccharieramzi/fastmri-reproducible-benchmark#173]
when I run paper_eval.py with cpu, it works but too slow. However, with gpu it reports errors like ‘GPU->CPU Memcpy failed’, how can I handle it?

![image](https://user-images.githubusercontent.com/37114053/156865936-f95d8488-34be-4c23-932a-fc2d9ec0a075.png)

**Comment by zaccharieramzi** [comment]
Hi @Jacksonm75 ,

Did you manage to fix this issue? If so can we close it?

**Comment by zaccharieramzi** [comment]
Closing this for clarity, but feel free to reopen if needed.
