### ISSUE TITLE
How to predict using the XPDNet-brain-af4 model

### ISSUE THREAD

**Issue by charmed-univie** [zaccharieramzi/fastmri-reproducible-benchmark#186]
Hi,
I've been trying to use your model [XPDNet-brain-af4](https://huggingface.co/zaccharieramzi/XPDNet-brain-af4) on the fastmri brain dataset. However, I'm stuck at how to assign the shape variable in 
```
model([
    kspace,  # shape: [n_slices, n_coils, n_rows, n_cols, 1]
    mask,  # shape: [n_slices, n_coils, n_rows, n_cols]
    smaps,  # shape: [n_slices, n_coils, n_rows, n_cols]
    shape,  # shape: [n_slices, 2]
])
```
When loading the datasets as in "fastmri_recon/evaluate/scripts/xpdnet_inference.py", only the kspace, mask and smaps is provided by the test_masked_kspace_dataset_from_indexable function.

Could you please help me?
Thank you!

**Comment by zaccharieramzi** [comment]
Hi @charmed-univie ,

Thanks for your interest in this work!
When you are using the brain models, you need to specify the shape of the output image as some cropping can happen for brain images.
In the `test_masked_kspace_dataset_from_indexable` there is a flag `output_shape_spec` that you need to set to `True` when considering brain data. You can see it set [here](https://github.com/zaccharieramzi/fastmri-reproducible-benchmark/blob/4a4ec09524437d11153fc5a525621783689bed38/fastmri_recon/evaluate/scripts/xpdnet_inference.py#L72C1-L73C1) in the `xpdnet_inference` function where you need to set a flag called `brain` to True when using brain data. If you are using the CLI directly, don't forget to to use the `-b` flag.

Hope this helps,
Cheers

**Comment by charmed-univie** [comment]
Hi,
Thank you, for the helpful response, the issue is resolved.
